### ISSUE TITLE
Multiple Dex files

### ISSUE THREAD

**Issue by SebLorea** [smartbeacon/smartbeacon-android-sdk#1]
Hi, 

I am trying to integrate your sdk into my android application but it doesn't work when I try to compile :

Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl

I see I have 2 different versions of Android Support-v4 lib in my Dexed Libs and I use the last one.
Can you please make sure you use the latest android-support-v4 ?

**Comment by smartbeacon** [comment]
HI,

We are releasing this week a new version of the Android SDK that fixes this issues and more.
New functionalities are also available.

Stay tunes on our blog ;)
— 
Brosso YING
SmartBeacon.eu
Paris : 0033681140115

**Comment by SebLorea** [comment]
Hey, thanks, it compiles fine now :)
